import { createElement } from '@lwc/engine-dom';
import CkB2BCatalog from 'c/ckB2BCatalog';

describe('c-ck-b-2-b-catalog', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-ck-b-2-b-catalog', {
            is: CkB2BCatalog
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});